# Site settings
title: Amber's Portfolio
email: artemisweng@gmail.com
description:
baseurl: /
domain_name: 'http://amberweng.com'
url:  'http://amberweng.com'
github_username:  artemisweng

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

